---
title: "Changelog"
---

## v. 0.0.1.4 (17-Aug-24)

Added internal function `clean_names()` to homogenize editors and authors names to the same standard for comparison reason. `clean_names()` incorporated to `guest_editor_info()` for name cleaning purposes, replacing previous code with similar purpose on `guest_editor_info()`

Fixed bug ignoring guest editor without profile link on `guest_editor_info()`\
\
Fixed code interpreting time of last submission on `guest_editor_info()`

Fixed and error generating duplicated guest editors in column rt_sum_vector2 generated by `guest_editor_info()`

`guest_editor_info()` now outputs a guest editor paper count for each special issue

`clean_names()` no longer replaces "dr" string inside names\
\
`special_issue_info()` allows now to target years of interest via `year=c(…)`

## v. 0.0.1.3 (10-Jan-23)

`guest_editor()` no longer part of `MDPIexploreR`. Use `special_issue_find()` and `guest_editor_info()` instead

Cleared errors and warnings for R CMD check

`articles_info()` replaced by `article_info()`.

`article_info()` transform editorial data to lowercase to facilitate the use of `gsub()`

## v. 0.0.1.2 (6-Jan-23)

Adding functions `special_issue_find()` & `guest_editor_info()` to deprecate `guest_editor()` and make the workflow more flexible.

## v. 0.0.1.1 (4-Jan-23)

`guest_editor()` now selects two first words of guest editors and authors names for comparison to account for discrepancies in number of surnames between guest editors and paper authors. (e.g. guest editor name = *Dr. Perico Palotes Fernández*, but author name is just *Perico Palotes*. ).

`guest_editor()` *d_over_deadline* output column now considers latest article submission date to a special issue instead of latest acceptance time.

`guest_editor()` Assoc. Prof. guest editors are now picked by the function too

`guest_editor()` Ignores papers of type "Editorial"

## v. 0.0.0.1 (Initial)
