utils::globalVariables(c(".",
                         "latest_sub",
                         "slash_number",
                         "txtProgressBar",
                         "setTxtProgressBar",
                         "Received",
                         "Accepted",
                         "tat",
                         "issue_type",
                         "year_month",
                         "mean_tat",
                         "Revised",
                         "open_peer_review"
                         ))